# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Checkout cads-forms-json repo
      uses: actions/checkout@v3
      with:
        repository: ecmwf-projects/cads-forms-json
        ref: dev
        token: ${{ secrets.CADS_PAT }}
        path: ./cads-forms-json
    
    - name: Checkout pycube repo
      uses: actions/checkout@v3
      with:
        repository: gbiavati/pycube
        ref: develop
        token: ${{ secrets.CADS_PAT }}
        path: ./pycube
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install git+https://github.com/ecmwf-projects/cads-api-client.git
        pip install ./pycube
    - name: fire with pycube a number of requests 
      run: |
        export FORMS_ROOT=./cads-forms-json
        export CADS_API_CREDENTIALS='{"url": "https://cads-cci.copernicus-climate.eu/api", "key": "9838d132-cd13-4ab0-8644-ac0152ce9838"}'
        pycube test-dataset --dataset reanalysis-era5-pressure-levels-cci --n 100
